In [4]:
import numpy as np
import pandas as pd


In [5]:
sights = pd.read_csv(r"/work/datasets/Sights.csv", sep=";")
sights

Sightseeings District.Name
0        Sagrada Família      Eixample
1             Park Güell        Gràcia
2              Casa Milà      Eixample
3            Caso Batlló      Eixample
4              La Rambla  Ciutat Vella
5          Museu Picasso  Ciutat Vella
6            La Catedral  Ciutat Vella
7               Camp Nou     Les Corts
8  Mercat de la Boqueria  Ciutat Vella

## Bus stops

In [6]:
bus_stops = pd.read_csv(r"/work/datasets/1.-Transportation/bus-stops.csv")
bus_stops

Code       Transport  Longitude   Latitude          Bus.Stop  \
0     K014    Day bus stop   2.171619  41.413744        BUS -192--   
1     K014    Day bus stop   2.134902  41.420222        BUS -124--   
2     K014    Day bus stop   2.162913  41.423187        BUS -117--   
3     K014    Day bus stop   2.163667  41.422899        BUS -117--   
4     K014    Day bus stop   2.120212  41.397209        BUS -130--   
...    ...             ...        ...        ...               ...   
3157  K014    Day bus stop   2.183887  41.422024        BUS -191--   
3158  K014    Day bus stop   2.176710  41.446419     BUS -127-81--   
3159  K015  Night bus stop   2.144596  41.411446      NITBUS -N4--   
3160  K014    Day bus stop   2.142256  41.371176  BUS -91-115-V5--   
3161  K015  Night bus stop   2.134932  41.398495      NITBUS -N7--   

            District.Name          Neighborhood.Name  
0          Horta-Guinardó                el Guinardó  
1                  Gràcia  Vallcarca i els Penitents  
2          Horta-Guinardó       la Font d'en Fargues  
3          Horta-Guinardó       la Font d'en Fargues  
4     Sarrià-Sant Gervasi                     Sarrià  
...                   ...                        ...  
3157          Sant Andreu   el Congrés i els Indians  
3158           Nou Barris               les Roquetes  
3159               Gràcia  Vallcarca i els Penitents  
3160       Sants-Montjuïc                 la Bordeta  
3161  Sarrià-Sant Gervasi     Sant Gervasi - Galvany  

[3162 rows x 7 columns]

In [7]:
bus_stops.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3162 entries, 0 to 3161
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Code               3162 non-null   object 
 1   Transport          3162 non-null   object 
 2   Longitude          3162 non-null   float64
 3   Latitude           3162 non-null   float64
 4   Bus.Stop           3162 non-null   object 
 5   District.Name      3146 non-null   object 
 6   Neighborhood.Name  3146 non-null   object 
dtypes: float64(2), object(5)
memory usage: 173.0+ KB


In [8]:
bus_stops.describe()

Longitude     Latitude
count  3162.000000  3162.000000
mean      2.159824    41.405002
std       0.027898     0.027150
min       2.055835    41.321643
25%       2.140627    41.386903
50%       2.161103    41.405734
75%       2.180406    41.423526
max       2.221753    41.467592

In [10]:
# Number of bus stops in each district
bus_stops['District.Name'].value_counts(dropna=False)

Sarrià-Sant Gervasi    439
Sants-Montjuïc         415
Eixample               405
Horta-Guinardó         389
Sant Martí             356
Nou Barris             330
Sant Andreu            228
Gràcia                 210
Les Corts              207
Ciutat Vella           167
NaN                     16
Name: District.Name, dtype: int64

In [11]:
#Bus stops without a district value
all_nulls_bus_stops = bus_stops.isnull().sum()
pd.DataFrame(all_nulls_bus_stops).transpose()

Code  Transport  Longitude  Latitude  Bus.Stop  District.Name  \
0     0          0          0         0         0             16   

   Neighborhood.Name  
0                 16

In [12]:
# Type of bus stops - Frequency table

bus_stops['Transport'].value_counts()

Day bus stop        2324
Night bus stop       828
Airport bus stop       7
Bus station            3
Name: Transport, dtype: int64

In [14]:
# Total bus stops

total_of_bus_stops = sum(bus_stops['Transport'].value_counts(dropna=True))


#public_transport_bus_merged



In [15]:
percentage_bus_stops = (bus_stops['Transport'].value_counts()/total_of_bus_stops)*100
percentage_bus_stops


pd.DataFrame(round(percentage_bus_stops.iloc[:], 2))

Transport
Day bus stop          73.50
Night bus stop        26.19
Airport bus stop       0.22
Bus station            0.09

In [47]:
#Number of bus stops in each neighborhood
neigh_bus_stops = bus_stops['Neighborhood.Name'].value_counts()
#neigh_bus_stops

#Percentage of bus stops in each in neighborhood
percentage_neigh_bus_stops = neigh_bus_stops/len(bus_stops['Neighborhood.Name'])

df_percentage_neigh_bus_stops = pd.DataFrame(round(percentage_neigh_bus_stops*100, 2))
df_percentage_neigh_bus_stops = df_percentage_neigh_bus_stops.reset_index()
df_percentage_neigh_bus_stops.columns  = ['Neighbourhood','Percentage']

#Name of the neighborhood with the highest percentage
our_index = df_percentage_neigh_bus_stops[ df_percentage_neigh_bus_stops['Percentage'] == 
df_percentage_neigh_bus_stops['Percentage'].max() ].index

max_stops_neigh = df_percentage_neigh_bus_stops.iloc[our_index,0]
#type(max_stops_neigh)
print('The neighborhood with the highest percentage of bus stops is: ',max_stops_neigh[0])


The neighborhood with the highest percentage of bus stops is:  la Dreta de l'Eixample


In [16]:
#Percentage of bus stops in a given district (compared to the total total bus stops) DENSITY
 
#Get the outliers of the number of bus stops per district (min and max)
#Calculate the mean _with_ the outliers _then_ show how it changes _without_ the outliers (?)

bus_stops_perDistrict = bus_stops['District.Name'].value_counts()/len(bus_stops['District.Name'])


pd.DataFrame(round(bus_stops_perDistrict.iloc[:]*100, 2))


District.Name
Sarrià-Sant Gervasi          13.88
Sants-Montjuïc               13.12
Eixample                     12.81
Horta-Guinardó               12.30
Sant Martí                   11.26
Nou Barris                   10.44
Sant Andreu                   7.21
Gràcia                        6.64
Les Corts                     6.55
Ciutat Vella                  5.28

------------------------------------

## Public Transport

In [17]:
public_transport = pd.read_csv(r"/work/datasets/1.-Transportation/public-transport.csv")
public_transport

Code         Transport  Longitude   Latitude  \
0    K001       Underground   2.119370  41.399203   
1    K001       Underground   2.135427  41.397791   
2    K001       Underground   2.185391  41.451492   
3    K001       Underground   2.174473  41.460889   
4    K001       Underground   2.168588  41.387200   
..    ...               ...        ...        ...   
646  K002     Railway (FGC)   2.118998  41.398967   
647  K008  Maritime station   2.175248  41.352808   
648  K008  Maritime station   2.174767  41.350955   
649  K002     Railway (FGC)   2.131188  41.397617   
650  K001       Underground   2.158822  41.375220   

                                               Station        District.Name  \
0    FGC (L6) - REINA ELISENDA (Sortida Duquesa d'O...  Sarrià-Sant Gervasi   
1                              FGC (L6) - LA BONANOVA-  Sarrià-Sant Gervasi   
2        METRO (L11) - CASA DE L'AIGUA (C. Vila-Real)-           Nou Barris   
3      METRO (L11) - CIUTAT MERIDIANA (C. Pedraforca)-           Nou Barris   
4           METRO (L1) - CATALUNYA (Rda. Universitat)-             Eixample   
..                                                 ...                  ...   
646                              FGC - REINA ELISENDA-  Sarrià-Sant Gervasi   
647                       Terminal Marítima E *Creuers       Sants-Montjuïc   
648                       Terminal Marítima D *Creuers       Sants-Montjuïc   
649                     FGC - LES TRES TORRES<center>-  Sarrià-Sant Gervasi   
650              METRO (L3) - POBLE SEC (C. de Manso)-             Eixample   

              Neighborhood.Name  
0                        Sarrià  
1        Sant Gervasi - Galvany  
2              la Trinitat Nova  
3              Ciutat Meridiana  
4        la Dreta de l'Eixample  
..                          ...  
646                      Sarrià  
647  la Marina del Prat Vermell  
648  la Marina del Prat Vermell  
649             les Tres Torres  
650                 Sant Antoni  

[651 rows x 7 columns]

----------

## Merged Data

In [18]:
public_transport_bus_merged = public_transport.merge(bus_stops, how='outer')
public_transport_bus_merged

Code       Transport  Longitude   Latitude  \
0     K001     Underground   2.119370  41.399203   
1     K001     Underground   2.135427  41.397791   
2     K001     Underground   2.185391  41.451492   
3     K001     Underground   2.174473  41.460889   
4     K001     Underground   2.168588  41.387200   
...    ...             ...        ...        ...   
3808  K014    Day bus stop   2.183887  41.422024   
3809  K014    Day bus stop   2.176710  41.446419   
3810  K015  Night bus stop   2.144596  41.411446   
3811  K014    Day bus stop   2.142256  41.371176   
3812  K015  Night bus stop   2.134932  41.398495   

                                                Station        District.Name  \
0     FGC (L6) - REINA ELISENDA (Sortida Duquesa d'O...  Sarrià-Sant Gervasi   
1                               FGC (L6) - LA BONANOVA-  Sarrià-Sant Gervasi   
2         METRO (L11) - CASA DE L'AIGUA (C. Vila-Real)-           Nou Barris   
3       METRO (L11) - CIUTAT MERIDIANA (C. Pedraforca)-           Nou Barris   
4            METRO (L1) - CATALUNYA (Rda. Universitat)-             Eixample   
...                                                 ...                  ...   
3808                                                NaN          Sant Andreu   
3809                                                NaN           Nou Barris   
3810                                                NaN               Gràcia   
3811                                                NaN       Sants-Montjuïc   
3812                                                NaN  Sarrià-Sant Gervasi   

              Neighborhood.Name          Bus.Stop  
0                        Sarrià               NaN  
1        Sant Gervasi - Galvany               NaN  
2              la Trinitat Nova               NaN  
3              Ciutat Meridiana               NaN  
4        la Dreta de l'Eixample               NaN  
...                         ...               ...  
3808   el Congrés i els Indians        BUS -191--  
3809               les Roquetes     BUS -127-81--  
3810  Vallcarca i els Penitents      NITBUS -N4--  
3811                 la Bordeta  BUS -91-115-V5--  
3812     Sant Gervasi - Galvany      NITBUS -N7--  

[3813 rows x 8 columns]

In [19]:
# Number of stops in each district

stops_district = public_transport_bus_merged['District.Name'].value_counts(dropna=False)

percentage_stops_perRegion = stops_district/len(public_transport_bus_merged)*100
pd.DataFrame(round(percentage_stops_perRegion.iloc[:], 2))

District.Name
Eixample                     13.77
Sarrià-Sant Gervasi          13.24
Sants-Montjuïc               12.27
Sant Martí                   11.17
Horta-Guinardó               11.01
Nou Barris                    9.68
Sant Andreu                   7.03
Les Corts                     6.06
Gràcia                        5.95
Ciutat Vella                  5.09
NaN                           4.72

In [20]:
# Frequency distribution of public transport:

ptrans_elements_district = public_transport_bus_merged['Transport'].value_counts(dropna=False)


percentage_ptrans_elements_district = ptrans_elements_district/len(public_transport_bus_merged)*100
pd.DataFrame(round(percentage_ptrans_elements_district.iloc[:], 2))


Transport
Day bus stop          60.95
Night bus stop        21.72
Underground           12.14
Tram                   1.70
Railway (FGC)          1.42
RENFE                  0.87
Maritime station       0.42
Airport train          0.24
Airport bus stop       0.18
Funicular              0.16
Cableway               0.13
Bus station            0.08

In [21]:
avg_per_region = bus_stops_perDistrict.describe()*100
print('The average percentage of bus stops per district is', round(avg_per_region.iloc[1], 3), '%')

The average percentage of bus stops per district is 9.949 %


In [22]:
#Percentage of missing values in columns: District and Neighborhood

all_nulls_bus_stops = bus_stops.isnull().sum()
percentage_missin_neigh_dist = (all_nulls_bus_stops/len(bus_stops))*100
pd.DataFrame(percentage_missin_neigh_dist).transpose()

Code  Transport  Longitude  Latitude  Bus.Stop  District.Name  \
0   0.0        0.0        0.0       0.0       0.0       0.506009   

   Neighborhood.Name  
0           0.506009

In [23]:
round(percentage_missin_neigh_dist.iloc[5], 3)
print("There's only a", round(percentage_missin_neigh_dist.iloc[5], 3),"% of missing values in District and Neighborhood columns.")

There's only a 0.506 % of missing values in District and Neighborhood columns.


## Density of bus stops per District

**We are going to find:**
<br>
** Bus Stops **
<br>
* Most dense District by bus stops - Sarrià-Sant Gervasi    439 stops
* Least dense District by bus stops - Ciutat Vella           167 stops
* Frequency distribution of bus stops:
- Day bus stop        2324
- Night bus stop       828
- Airport bus stop       7
- Bus station            3

Frequency table of Bus stops by District.

Sarrià-Sant Gervasi    439
Sants-Montjuïc         415
Eixample               405
Horta-Guinardó         389
Sant Martí             356
Nou Barris             330
Sant Andreu            228
Gràcia                 210
Les Corts              207
Ciutat Vella           167
NaN                     16

<br>

** Public Transport **
<br>
* Most dense District - Eixample         525
* Least dense District - Ciutat Vella     194
* Frequency distribution of public transport:
- Bus stops           3162
- Underground         463
- Tram                 65
- Railway (FGC)        54
- RENFE                33
- Maritime station     16
- Airport train         9
- Funicular             6
- Cableway              5 

Missing values in public Transport data set = 167 NaN We checked a few of the cases and saw that all of them were stops, that are not in Barcelona. 
Missing values in bus stops = 16
Total missing values = 180 

Frequency table of Public transport by District (public + bus).

Eixample               525
Sarrià-Sant Gervasi    505
Sants-Montjuïc         468
Sant Martí             426
Horta-Guinardó         420
Nou Barris             369
Sant Andreu            268
Les Corts              231
Gràcia                 227
Ciutat Vella           194
NaN                    180



<br>


**We assume reasons for a District being the _most_ dense:**
<br>
- Sightseeing elements
- Cultural importance
- Administrative importance (Town Hall, Main Post Office, etc)
- Population
- Higher per capita income 
- High population
- Size of district
- ...
<br>
**We assume reasons for a District being the _least_ dense:**
<br>
* Minimum cultural, sightseeing, administrative importance
* Properties of said district do not allow same investment in public transportation elements (Old Town for example)
* Distance from city center
* Close to other very dense district
* Low population
* Size of district
* ...
<br>

**Top 3 Most dense districts by bus stops**:
<br>
- Sarrià-Sant Gervasi    439 stops
- Sants-Montjuïc         415 stops
- Eixample               405 stops
<br>
**Top 3 Least dense districts by bus stops**:
<br>
- Gràcia                 210 stops
- Les Corts              207 stops
- Ciutat Vella           167 stops
<br>

**Top 3 Most dense district by public transport stops**:
<br>
- Eixample               525 stops
- Sarrià-Sant Gervasi    505 stops
- Sants-Montjuïc         468 stops
<br>
**Top 3 Least dense district by public transport stops**:
<br>
- Les Corts              231 stops
- Gràcia                 227 stops
- Ciutat Vella           194 stops
<br>


**Properties of _most_ and _least_ dense:**
<br>
Sarrià-Sant Gervasi
<br>
* Highest income per capita district in Barcelona
* Highest proportion of bachelor's degrees
* Lowest unemployment rate (next to the neighborhing district of Les Corts)
* Lowest presence of foreigners
* Situated in the western limit of the city
<br>
Ciutat Vella
<br>
* Historical city center
* ...
<br>

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=c0070a7d-7e19-41ed-914b-a87e6b811e61' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>